version: '3.3'
services:
  document_postgres:
    image: postgres
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 5050:80
    depends_on:
      - document_postgres
